version: "3.8"

services:
  # Nome do nosso serviço
  order_manager_marketplace:
    # IMPORTANTE: A imagem deve ser construída manualmente na VPS antes do deploy.
    # O Portainer usará esta imagem que já existe localmente.
    # O nome da imagem é 'order_manager_marketplace-frontend:latest'
    image: order_manager_marketplace:latest
    networks:
      # Conecta o serviço à rede do Traefik
      - traefik_public
      - app_network
    deploy:
      restart_policy:
        condition: any
      labels:
        # --- Configurações do Traefik ---
        - "traefik.enable=true"

        # --- Roteador para app.neobrasil.acontece.ai ---
        - "traefik.http.routers.order_manager_marketplace-secure.rule=Host(`app.neobrasil.acontece.ai`)"
        - "traefik.http.routers.order_manager_marketplace-secure.entrypoints=websecure"
        - "traefik.http.routers.order_manager_marketplace-secure.tls=true"
        - "traefik.http.routers.order_manager_marketplace-secure.tls.certresolver=zerosslresolver"
        - "traefik.http.routers.order_manager_marketplace-secure.service=order_manager_marketplace-service"

        # --- Serviço do Traefik ---
        - "traefik.http.services.order_manager_marketplace-service.loadbalancer.server.port=80"
        - "traefik.http.services.order_manager_marketplace-service.loadbalancer.passHostHeader=true"

networks:
  # Declara que a rede é externa, pois ela já foi criada pelo Traefik
  traefik_public:
    external: true
    name: externa
  app_network:
    external: true
    name: interna
