version: '3.8'

services:
  # Nome do nosso serviço
  gerenciador-post:
    # IMPORTANTE: A imagem deve ser construída manualmente na VPS antes do deploy.
    # O Portainer usará esta imagem que já existe localmente.
    # O nome da imagem é 'gerenciador-post-frontend:latest'
    image: gerenciador-post:latest
    networks:
      # Conecta o serviço à rede do Traefik
      - StoreProDigitalNet
    deploy:
      restart_policy:
        condition: any
      labels:
        # --- Configurações do Traefik ---
        - "traefik.enable=true"
        - "traefik.docker.network=StoreProDigitalNet"

        # --- Roteador para app.storeprodigital.site ---
        - "traefik.http.routers.gerenciador-post-secure.rule=Host(`app.storeprodigital.site`)"
        - "traefik.http.routers.gerenciador-post-secure.entrypoints=websecure"
        - "traefik.http.routers.gerenciador-post-secure.tls=true"
        - "traefik.http.routers.gerenciador-post-secure.tls.certresolver=zerosslresolver"
        - "traefik.http.routers.gerenciador-post-secure.service=gerenciador-post-service"

        # --- Serviço do Traefik ---
        - "traefik.http.services.gerenciador-post-service.loadbalancer.server.port=80"
        - "traefik.http.services.gerenciador-post-service.loadbalancer.passHostHeader=true"

networks:
  # Declara que a rede é externa, pois ela já foi criada pelo Traefik
  StoreProDigitalNet:
    external: true